<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Route;

class GenerateZiggyTypes extends Command
{
    protected $signature = 'ziggy:generate-types';
    protected $description = 'Generate Ziggy types file based on current routes';

    public function handle()
    {
        $routes = collect(Route::getRoutes()->getRoutes())
            ->filter(function ($route) {
                return $route->getName() && !str_starts_with($route->getName(), 'generated::');
            })
            ->mapWithKeys(function ($route) {
                $parameters = collect($route->parameterNames())
                    ->map(function ($param) use ($route) {
                        return [
                            'name' => $param,
                            'required' => !in_array($param, $route->parameterNames() ?: [])
                        ];
                    })
                    ->values()
                    ->toArray();

                return [$route->getName() => $parameters];
            })
            ->toArray();

        $types = $this->generateTypesFile($routes);

        $path = resource_path('js/types/ziggy.d.ts');
        file_put_contents($path, $types);

        $this->info('Ziggy types generated successfully!');
        $this->info("File: {$path}");

        return Command::SUCCESS;
    }

    private function generateTypesFile(array $routes): string
    {
        $routesArray = $this->formatRoutesArray($routes);

        return <<<TYPES
/* This file is generated by ziggy:generate-types */
declare module 'ziggy-js' {
    interface RouteList {
{$routesArray}
    }
}
export { };

// Declaración para Laravel Vite Plugin
declare module "laravel-vite-plugin/inertia-helpers" {
    export function resolvePageComponent(path: string, pages: any): any;
}
TYPES;
    }

    private function formatRoutesArray(array $routes): string
    {
        $output = '';

        foreach ($routes as $name => $parameters) {
            $output .= "        \"{$name}\": ";

            if (empty($parameters)) {
                $output .= "[],\n";
            } else {
                $paramsOutput = '';
                foreach ($parameters as $param) {
                    $required = $param['required'] ? 'true' : 'false';
                    $paramsOutput .= "            {\n";
                    $paramsOutput .= "                \"name\": \"{$param['name']}\",\n";
                    $paramsOutput .= "                \"required\": {$required}\n";
                    $paramsOutput .= "            },\n";
                }
                $output .= "[\n{$paramsOutput}        ],\n";
            }
        }

        return $output;
    }
}
