/* This file is generated by ziggy:generate-types */
declare module 'ziggy-js' {
    interface RouteList {
        "sanctum.csrf-cookie": [],
        "welcome": [],
        "login": [],
        "adviser.login": [],
        "register": [],
        "verify.show": [],
        "verify.store": [],
        "inicio": [],
        "logout": [],
        "dashboard": [],
        "perfil": [],
        "storage.local": [
            {
                "name": "path",
                "required": false
            },
        ],

    }
}
export { };

// Declaración para Laravel Vite Plugin
declare module "laravel-vite-plugin/inertia-helpers" {
    export function resolvePageComponent(path: string, pages: any): any;
}